$(function () {
    
    //configuration attributes of OData provider
    var oProviderConfig = {
        name: 'oData',
        oDataServiceHost: 'http://localhost:9000/odata'
    };
    var NorthwindContext = $data('JayStack.NorthwindContext')

    var northwindRemote;
    var northwind;


    /*
    // OPTION 1
    // managing entities through OData endpoint*/
    // var northwind = new NorthwindContext(oProviderConfig);

    // northwind.onReady(function () {
    //     $('form').bind('submit', saveProduct);
    //     northwind.Categories.toArray(app.renderCategories);
    // });
    // END OF OPTION 1

    function Application() {
        var self = this;

        self.renderCategories = function (dataList) {
            var table = $('#categoryTable tbody');
            table.empty();
            dataList.forEach(function (item) {
                table.append('<tr><td><a onClick="app.loadProduct(' + item.Id + ')">' +
                    item.Name + '</a></td><td>' + item.Description + '</td></tr>');
            });
        }

        self.loadProduct = function (categoryId) {
            northwind.Products
                .filter(function (product) { return product.CategoryId == this.Id },
                { Id: categoryId })
                .toArray(self.renderProducts);
        }

        self.renderProducts = function (dataList) {
            $('.well-box').hide();
            $('#productTable').show();
            var table = $('#productTable tbody');
            table.empty();
            dataList.forEach(function (item) {
                table.append('<tr><td><a onClick="app.editProduct(' + item.Id + ')">'
                    + item.Name + '</a></td>'
                    + '<td>' + item.QuantityPerUnit + '</td>'
                    + '<td>' + item.UnitPrice + '</td>'
                    + '<td>' + item.Discontinued + '</td></tr>');
            });
        }
        self.editProduct = function (productId) {
            northwind.Products
                .single(function (product) { return product.Id == this.Id }, { Id: productId }, self.renderEditProduct);
        }
        self.renderEditProduct = function (product) {
            window.selectedProduct = product;
            $('form').serializeArray().forEach(function (item) {
                $('form [name="' + item.name + '"]').val(product[item.name]);
            });
            $('form [name="Discontinued"]').prop('checked', product['Discontinued']);
            $('.well-box').show();
        }

    }


    /*
    // OPTION 2
    // sync entities from OData datasource to local DB using using static model
    initialize the Northwind context from the static data model generated by JaySvcUtil.exe*/
    //var NorthwindContext = $data('JayStack.NorthwindContext')
    
    // var remoteDB = new NorthwindContext(oProviderConfig);
    // northwindRemote = remoteDB;
    // remoteDB.onReady(function () {
    //     var localDB = new NorthwindContext({ name: 'webSql', databaseName: 'Northwind' });
    //     northwind = localDB;

    //     localDB.onReady(function(){
    //         resetLocal()
    //         .then(sync)
    //         .then(function() {
    //             $('form').bind('submit', saveProduct);
    //             return northwind.Categories.toArray(renderCategories);
    //         })
    //         .fail(function (reason) {
    //             console.log(reason);
    //         });
         
    //     });
    // });
    // END OF OPTION 2
    

    // OPTION 3
    //sync entities from OData datasource to local DB using dynamic model
    $data.initService(oProviderConfig.oDataServiceHost)
        .then(function (remoteDB, contextFactory, contexType) {
            northwindRemote = remoteDB;

            var localDB = contextFactory({ name: 'local', databaseName: 'Northwind' });
            northwind = localDB;
            
            remoteDB.onReady(function() {
                console.log(remoteDB.contextType);
                localDB.onReady(function(){
                    resetLocal()
                    .then(sync)
                    .then(function () {
                        $('form').bind('submit', saveProduct);
                        return northwind.Categories.toArray(renderCategories);
                    })
                    .fail(function (reason) {
                        console.log(reason);
                    });
                });
                
            });

        });
    // END OF OPTION 3

    window['app'] = new Application();
    
    //clears entities from local database
    function resetLocal() {
        return northwind.Categories.toArray()
            .then(function(categories) {
                categories.forEach(function (c) { northwind.Categories.remove(c); });
            })
            .then(function() {
                console.log("a")
                return northwindRemote.Products.toArray()
                    .then(function (products) {
                        products.forEach(function(p) {northwind.Products.remove(p)})
                    })
            })
            .then(function() {
                return northwind.saveChanges();
            })
    }

    //sync entities from OData to local database
    function sync() {
        return northwindRemote.Categories.toArray()
                .then(function (categories) {
                    northwind.Categories.addMany(categories);
                })
                .then(function (){
                    return northwindRemote.Products.toArray()
                    .then(function (products) {
                        northwind.Products.addMany(products);
                    })
                })
                .then(function(){
                    return northwind.saveChanges();
                })
            
    }

    function renderCategories(dataList) {
        var table = $('#categoryTable tbody');
        table.empty();
        dataList.forEach(function (item) {
            table.append('<tr><td><a onClick="app.loadProduct(' + item.Id + ')">' +
                item.Name + '</a></td><td>' + item.Description + '</td></tr>');
        });
    }



    function saveProduct() {
        //attach the selected product entity to JayData context
        northwind.Products.attach(selectedProduct);

        //collect the values from the form and 
        //modify the properties of our local entity
        $('form').serializeArray().forEach(function (item) {
            selectedProduct[item.name] = $('form [name="' + item.name + '"]').val();
        });
        selectedProduct.Discontinued = !!$('form [name = "Discontinued"]').is(':checked');
        //save the modified product to our remote database through OData using JayData 
        northwind.saveChanges();

        //display a message to the user
        var result = $('#saveResult');
        result.show();
        setTimeout(function () {
            result.fadeOut("slow");
        }, 1500);
        return false;
    }
});